# Generated by Django 4.1.4 on 2023-01-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hos_name3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
