# Generated by Django 4.1.4 on 2023-01-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ambulance_patient_ambulance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='amb_number2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='amb_number3',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='chemist_number2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='chemist_number3',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_number1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_number2',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
