# Generated by Django 4.1.4 on 2023-01-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ambulance_amb_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='amb_name2',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='amb_name3',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
